### ISSUE TITLE
Switch augmentations backend to `kornia`

### ISSUE THREAD

**Issue by aaprasad** [talmolab/dreem#72]
We should try switching our augmentations library to [`kornia`](https://kornia.readthedocs.io/en/latest/index.html) as it allows for gpu accelerated augmentations which will be important since we have to augment entire images instead of just crops. If we do switch to kornia, it might be a good idea to switch the video reading backend to [`decord`](https://github.com/dmlc/decord) or another video backend that allows reading directly to tensors.

**Comment by talmo** [comment]
FYI, in `sleap-nn` (and in consultation with others who have developed similar pipelines), we actually found kornia on the GPU to be slower than CPU-based augmentation. Maybe the bottlenecks are different here though?

I think it's all because during training, the GPU is better used for just doing the optimization and using the CPU parallelism to improve overall throughput. CPU kornia also seems to be solid.

It might still be better to do optical flow on the GPU using kornia since it can then happen after preprocessing but before the forward pass.

In testing decord, I also found the differences to be pretty negligible in the video decoding performance, especially if you defer casting the `uint8` frames to `float32` until _after_ you move the images to the GPU.
